### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by Andrejki** [AbirHasan2005/OPRecon#10]
Hello.
It is not working. I have all the requirements installed, PIP, etc., I am on Ubuntu.
It shows me the first menu to choose from options. I choose e.g. "Find information via phone number":
Then I enter the phone number in international format:
And the output I get after several minutes is next.
Does anyone have a fix?
Regards

  File "/home/andrejki/.local/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/andrejki/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/andrejki/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andrejki/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/andrejki/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/andrejki/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/home/andrejki/.local/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/andrejki/.local/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f67e3b7b760>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andrejki/.local/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/home/andrejki/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/home/andrejki/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='restcountries.eu', port=443): Max retries exceeded with url: /rest/v2/callingcode/381 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f67e3b7b760>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "files/phoneinfoga.py", line 569, in <module>
    scanNumber(args.number)
  File "files/phoneinfoga.py", line 522, in scanNumber
    localScan(InputNumber)
  File "files/phoneinfoga.py", line 239, in localScan
    countryRequest = json.loads(requests.request('GET', 'https://restcountries.eu/rest/v2/callingcode/{}'.format(numberCountryCode.replace('+', ''))).content)
  File "/home/andrejki/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/andrejki/.local/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/andrejki/.local/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/andrejki/.local/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='restcountries.eu', port=443): Max retries exceeded with url: /rest/v2/callingcode/381 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f67e3b7b760>: Failed to establish a new connection: [Errno 110] Connection timed out'))

**Comment by Andrejki** [comment]
Noone has a fix?

**Comment by rajatumrao** [comment]
Same error for me as well

**Comment by ActivateLLC** [comment]
#gottem!! smh.
