### ISSUE TITLE
Country code

### ISSUE THREAD

**Issue by kanima25** [AbirHasan2005/OPRecon#2]
How to enter a valid command with country code?

**Comment by AbirHasan2005** [comment]
What!??
Explain Properly.

**Comment by kofi2406** [comment]
Hi Well i have a problem with the country code i am trying to get or let say track a number in a country called ghana and the there country code is +233 but when i add it and the input in the number they give me an error like this T
raceback (most recent call last):                                     
  File "/root/OPRecon/files/tracker.py", line 103, in <module>         
    main()                                                             
  File "/root/OPRecon/files/tracker.py", line 50, in main              
    country_code = obj['country_code']                                 
KeyError: 'country_code'

**Comment by usethisname1419** [comment]
i having same error,... it seems this is full of bugs

**Comment by supermanindie** [comment]
Traceback (most recent call last):                                                            
  File "/home/kali/OPRecon/files/tracker.py", line 103, in <module>                           
    main()                                                                                    
  File "/home/kali/OPRecon/files/tracker.py", line 50, in main                                
    country_code = obj['country_code']                                                        
                   ~~~^^^^^^^^^^^^^^^^                                                        
KeyError: 'country_code'

**Comment by Tin-7Tin** [comment]
same issue

**Comment by Rkcoder0425** [comment]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/OPRecon/files/tracker.py", line 103, in <module>
    main()
  File "/data/data/com.termux/files/home/OPRecon/files/tracker.py", line 50, in main
    country_code = obj['country_code']
                   ~~~^^^^^^^^^^^^^^^^
KeyError: 'country_code'

Same error

**Comment by Doujinx28** [comment]
I really cant understood resolving that error. Tabs are rigts, space, indenation. He wrote evyrthing good, no mistakes. Maybe json imported in python project, on project onwer pycharm impot json good, but in our env json isnt imported, same seen when i open tracker.py and urlib or try pip install json.

**Comment by Doujinx28** [comment]
I dont that moment, tabs, spaces, and make then 3 or 4. Option to change indenation on something copilot called "special idenandation". First time hear that.
