### ISSUE TITLE
It never finds location

### ISSUE THREAD

**Issue by NicolettaBrundo** [AbirHasan2005/OPRecon#6]

**Comment by NicolettaBrundo** [comment]
*] Running local scan ...
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x732b7cfeb0>, 'Connection to restcountries.eu timed out. (connect timeout=None)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='restcountries.eu', port=443): Max retries exceeded with url: /rest/v2/callingcode/39 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x732b7cfeb0>, 'Connection to restcountries.eu timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/OPRecon/files/phoneinfoga.py", line 569, in <module>
    scanNumber(args.number)
  File "/data/data/com.termux/files/home/OPRecon/files/phoneinfoga.py", line 522, in scanNumber
    localScan(InputNumber)
  File "/data/data/com.termux/files/home/OPRecon/files/phoneinfoga.py", line 239, in localScan
    countryRequest = json.loads(requests.request('GET', 'https://restcountries.eu/rest/v2/callingcode/{}'.format(numberCountryCode.replace('+', ''))).content)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, send_kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='restcountries.eu', port=443): Max retries exceeded with url: /rest/v2/callingcode/39 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x732b7cfeb0>, 'Connection to restcountries.eu timed out. (connect timeout=None)'))

**Comment by AbirHasan2005** [comment]
Maybe your network problem 🤔

**Comment by NicolettaBrundo** [comment]
What kind of problema?

Il ven 5 nov 2021, 07:35 Abir Hasan ***@***.***> ha scritto:

**Comment by romualready** [comment]
I have the same problem when i use the first command

**Comment by Naj143** [comment]
How we can see that file

**Comment by 9546526900** [comment]
This is a fake atlist Nothing ...

# When use  **cd OPRecon**
