### ISSUE TITLE
Great Job Here's how it works

### ISSUE THREAD

**Issue by ChillVibesMushroom** [AbirHasan2005/OPRecon#9]
Make sure to have python installed and pip installed and that you're running from the f droid Termux repo list to avoid any issues use grimlers repository package

apt update

Follow the steps to install the oprecon repo

Make sure to type your phone number with the right code according to your country

Example US +10000000000

I'm still messing with it but that's the basics

**Comment by ChillVibesMushroom** [comment]
![Screenshot_20220404-010750-458](https://user-images.githubusercontent.com/99580833/161483475-2077a643-2a7d-40ab-9648-6d8ca7cacab1.png)

**Comment by ChillVibesMushroom** [comment]
![Screenshot_20220404-011007-123](https://user-images.githubusercontent.com/99580833/161483696-d030d7ac-dc23-48aa-bdda-0d2844164d0d.png)

**Comment by ChillVibesMushroom** [comment]
![Screenshot_20220404-011206-489](https://user-images.githubusercontent.com/99580833/161483924-a950f1eb-700e-48b2-8ce1-67ddefe69057.png)

**Comment by MrS3rv3r404** [comment]
Getting Location             [ FAILED ]

Bro can you fix it?

**Comment by Rkcoder0425** [comment]
Bro can't track a number
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/OPRecon/files/tracker.py", line 103, in <module>
    main()
  File "/data/data/com.termux/files/home/OPRecon/files/tracker.py", line 50, in main
    country_code = obj['country_code']
                   ~~~^^^^^^^^^^^^^^^^
KeyError: 'country_code'
